/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/status": {
    get: operations["healthcheck_status_get"];
  };
  "/annotation/{pdf_file_name}": {
    get: operations["get_annotated_pdf_annotation__pdf_file_name__get"];
  };
  "/search": {
    post: operations["search_search_post"];
  };
}

export interface components {
  schemas: {
    HTTPValidationError: {
      detail?: components["schemas"]["ValidationError"][];
    };
    JinaData: {
      name?: string;
      id?: string;
      score?: number;
      page?: string;
      pdf?: string;
      pdf_name?: string;
      thumbnail?: string;
      coordinates?: number[];
      tags?: { [key: string]: unknown };
      annotated_pdf?: string;
    };
    MatchData: {
      data?: components["schemas"]["JinaData"][];
    };
    SearchData: {
      mime_type?: string;
      data?: string;
    };
    ValidationError: {
      loc: string[];
      msg: string;
      type: string;
    };
  };
}

export interface operations {
  healthcheck_status_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
    };
  };
  get_annotated_pdf_annotation__pdf_file_name__get: {
    parameters: {
      path: {
        pdf_file_name: { [key: string]: unknown };
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  search_search_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MatchData"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SearchData"];
      };
    };
  };
}

export interface external {}
